# Import liberaries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

# Import dataset

In [2]:
ds_houses = pd.read_csv('/kaggle/input/house-price-dataset/housing.csv')

In [3]:
ds_houses

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

# Dataset description

In [4]:
ds_houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [5]:
ds_houses.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [6]:
pd.isnull(ds_houses).sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [7]:
ds_houses.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   
5    -122.25     37.85                52.0        919.0           213.0   
6    -122.25     37.84                52.0       2535.0           489.0   
7    -122.25     37.84                52.0       3104.0           687.0   
8    -122.26     37.84                42.0       2555.0           665.0   
9    -122.25     37.84                52.0       3549.0           707.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  
5       413.0       193.0         4.0368            269700.0        NEAR BAY  
6      1094.0       514.0         3.6591            299200.0        NEAR BAY  
7      1157.0       647.0         3.1200            241400.0        NEAR BAY  
8      1206.0       595.0         2.0804            226700.0        NEAR BAY  
9      1551.0       714.0         3.6912            261100.0        NEAR BAY

In [8]:
ds_houses.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20630    -121.32     39.29                11.0       2640.0           505.0   
20631    -121.40     39.33                15.0       2655.0           493.0   
20632    -121.45     39.26                15.0       2319.0           416.0   
20633    -121.53     39.19                27.0       2080.0           412.0   
20634    -121.56     39.27                28.0       2332.0           395.0   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20630      1257.0       445.0         3.5673            112000.0   
20631      1200.0       432.0         3.5179            107200.0   
20632      1047.0       385.0         3.1250            115600.0   
20633      1082.0       382.0         2.5495             98300.0   
20634      1041.0       344.0         3.7125            116800.0   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20630          INLAND  
20631          INLAND  
20632          INLAND  
20633          INLAND  
20634          INLAND  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

In [9]:
ds_houses.sample(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2504     -120.45     36.86                34.0        673.0           173.0   
16747    -122.46     37.69                35.0       1983.0           385.0   
2340     -119.67     36.81                 4.0       1262.0           216.0   
17126    -122.13     37.46                31.0       2247.0           573.0   
13840    -117.30     34.54                25.0       2546.0           488.0   
14129    -117.09     32.75                20.0       1701.0           503.0   
1424     -122.03     37.98                16.0       1209.0           477.0   
1315     -121.79     37.99                18.0       3646.0           534.0   
15115    -117.01     32.85                23.0       2592.0           414.0   
17777    -121.85     37.38                12.0      12980.0          2568.0   

       population  households  median_income  median_house_value  \
2504        539.0       182.0         2.3523             66000.0   
16747      1577.0       414.0         4.0833            266700.0   
2340        622.0       199.0         4.9432            114400.0   
17126      1711.0       511.0         3.2642            185600.0   
13840      1338.0       487.0         3.2596             85400.0   
14129      1482.0       465.0         1.6789             95500.0   
1424        627.0       482.0         1.3894            156300.0   
1315       1651.0       535.0         5.7321            164700.0   
15115      1401.0       431.0         5.4903            151400.0   
17777      8190.0      2515.0         5.2415            286500.0   

      ocean_proximity  
2504           INLAND  
16747      NEAR OCEAN  
2340           INLAND  
17126        NEAR BAY  
13840          INLAND  
14129      NEAR OCEAN  
1424         NEAR BAY  
1315           INLAND  
15115       <1H OCEAN  
17777       <1H OCEAN

# Split data into features and target

In [10]:
X = ds_houses.drop(['median_house_value'], inplace=False, axis=1)
X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income ocean_proximity  
0           322.0       126.0         8.3252        NEAR BAY  
1          2401.0      1138.0         8.3014        NEAR BAY  
2           496.0       177.0         7.2574        NEAR BAY  
3           558.0       219.0         5.6431        NEAR BAY  
4           565.0       259.0         3.8462        NEAR BAY  
...           ...         ...            ...             ...  
20635       845.0       330.0         1.5603          INLAND  
20636       356.0       114.0         2.5568          INLAND  
20637      1007.0       433.0         1.7000          INLAND  
20638       741.0       349.0         1.8672          INLAND  
20639      1387.0       530.0         2.3886          INLAND  

[20640 rows x 9 columns]

In [11]:
y = ds_houses['median_house_value']
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [12]:
X1 = X.iloc[:,:].values

y1 = y.iloc[:].values

In [13]:
print(X1)
print('============================================')
print(y1)

[[-122.23 37.88 41.0 ... 126.0 8.3252 'NEAR BAY']
 [-122.22 37.86 21.0 ... 1138.0 8.3014 'NEAR BAY']
 [-122.24 37.85 52.0 ... 177.0 7.2574 'NEAR BAY']
 ...
 [-121.22 39.43 17.0 ... 433.0 1.7 'INLAND']
 [-121.32 39.43 18.0 ... 349.0 1.8672 'INLAND']
 [-121.24 39.37 16.0 ... 530.0 2.3886 'INLAND']]
[452600. 358500. 352100. ...  92300.  84700.  89400.]


In [14]:
pd.isnull(X1).sum()

207

# Deal with null values

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.nan, strategy='mean')
imputer = imputer.fit(X1[:, 4:5])
X1 [:, 4:5] = imputer.transform(X1[:, 4:5])

In [16]:
pd.isnull(X1).sum()

0

# Convert the category data to numerical data

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X2 = np.array(ct.fit_transform(X1))

In [18]:
print(X2)

[[0.0 0.0 0.0 ... 322.0 126.0 8.3252]
 [0.0 0.0 0.0 ... 2401.0 1138.0 8.3014]
 [0.0 0.0 0.0 ... 496.0 177.0 7.2574]
 ...
 [0.0 1.0 0.0 ... 1007.0 433.0 1.7]
 [0.0 1.0 0.0 ... 741.0 349.0 1.8672]
 [0.0 1.0 0.0 ... 1387.0 530.0 2.3886]]


# Scalling the numerical data

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X2[:, 5:] = sc.fit_transform(X2[:, 5:])

In [20]:
print(X2)

[[0.0 0.0 0.0 ... -0.9744285971768438 -0.9770328537634606
  2.344765758301686]
 [0.0 0.0 0.0 ... 0.8614388682720715 1.669961027564066 2.3322379635373007]
 [0.0 0.0 0.0 ... -0.8207773518723169 -0.8436369170562433
  1.7826994032844703]
 ...
 [0.0 1.0 0.0 ... -0.3695372004320112 -0.17404162691805483
  -1.1425933119924276]
 [0.0 1.0 0.0 ... -0.6044293340584718 -0.3937525814946479
  -1.0545829218829705]
 [0.0 1.0 0.0 ... -0.03397700953706758 0.07967221348586817
  -0.7801294685153212]]


In [21]:
y2 = y1.reshape(-1,1)

In [22]:
print(y2)

[[452600.]
 [358500.]
 [352100.]
 ...
 [ 92300.]
 [ 84700.]
 [ 89400.]]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
y3 = sc.fit_transform(y2)

In [24]:
print(y3)

[[ 2.12963148]
 [ 1.31415614]
 [ 1.25869341]
 ...
 [-0.99274649]
 [-1.05860847]
 [-1.01787803]]


# Split data into train and test data

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X2, y3, test_size = 0.3, random_state = 42)

In [26]:
print('X trian =', X_train)
print('=============================================================')
print('X test =', X_test)
print('=============================================================')
print('y train =', y_train)
print('=============================================================')
print('y test =', y_test)

X trian = [[1.0 0.0 0.0 ... -0.18321298917192408 -0.2394317919706123
  0.13713671452738266]
 [0.0 0.0 0.0 ... -0.3766016255034837 -0.009258410985609998
  -0.5303631401245469]
 [0.0 0.0 0.0 ... -0.6132598653978124 -0.5611514040291951
  0.17472009882053632]
 ...
 [1.0 0.0 0.0 ... 0.29186959688460135 0.07182539367956127
  -0.4928323936245212]
 [1.0 0.0 0.0 ... 0.3104137126972167 0.15552480494683482
  0.9730248693947153]
 [0.0 0.0 0.0 ... 1.053944451469697 1.941984114182705 -0.6817494331597138]]
X test = [[0.0 1.0 0.0 ... -0.029561743867397273 -0.36759651547362493
  -1.1524892171004288]
 [0.0 1.0 0.0 ... 0.12320644830319548 0.2209149699993923
  -0.7050153377221421]
 [0.0 0.0 0.0 ... -0.10197210084999037 1.2122298721961635
  -0.205587956526849]
 ...
 [1.0 0.0 0.0 ... 3.1688567072417757 4.228024284420115
  -0.18879650051912372]
 [0.0 1.0 0.0 ... 3.982148643595047 3.069310559688796 -0.116156346002945]
 [1.0 0.0 0.0 ... 2.375874992968988 2.810365506080668
  -0.43093034890638626]]
y train = [[-

# Try the linear regression 

**Training the model**

In [27]:
from sklearn.linear_model import LinearRegression
linregressor = LinearRegression()
linregressor.fit(X_train, y_train)

LinearRegression()

**Predicting the results**

In [28]:
y_pred = linregressor.predict(X_test)
print(y_pred)

[[-1.22973633]
 [-0.63623047]
 [ 0.49365234]
 ...
 [ 0.67651367]
 [-0.80200195]
 [ 0.11254883]]


# Test the model score

In [29]:
print(linregressor.score(X_test , y_test)*100)

63.95558873763583


In [30]:
print(linregressor.score(X_train , y_train)*100)

64.70293520163712


# Try the polynomial regression

**Training the model**

In [31]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

**Predicting the results**

In [32]:
y_predp = lin_reg_2.predict(poly_reg.fit_transform(X_test))
print(y_predp)

[[ -1.23562371]
 [ -0.59758165]
 [-36.33180787]
 ...
 [ -0.08958947]
 [ -0.83116372]
 [ -0.47728206]]
